### ISSUE TITLE
error on RandomForest fit with mock data

### ISSUE THREAD

**Issue by N950** [AlCorreia/GeFs#4]
The traceback seems to cut off at trees.py line 504, the rest I couldn't identify where the problem is

Traceback (most recent call last):
  File "model_gefs.py", line 471, in <module>
    test()
  File "model_gefs.py", line 343, in test
    test_helper(m['model_pars'], m['data_pars'], m['compute_pars'])
  File "model_gefs.py", line 352, in test_helper
    fit(data_pars=data_pars, compute_pars=compute_pars, out_pars=None)
  File "model_gefs.py", line 93, in fit
    model.model.fit(Xtrain.values, ytrain.values)
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\trees.py", line 504, in fit
    self.surrogate)
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\numba\core\dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\numba\core\dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\numba\core\utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(array(int64, 1d, C), array(bool, 2d, C))

There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(array(int64, 1d, C), array(bool, 2d, C))':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 162.
    With argument(s): '(array(int64, 1d, C), array(bool, 2d, C))':
   Rejected as the implementation raised a specific error:
     TypeError: unsupported array index type array(bool, 2d, C) in [array(bool, 2d, C)]
  raised from C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\numba\core\typing\arraydecl.py:69

During: typing of intrinsic-call at C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\utils.py (32)

File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\utils.py", line 32:
def resample_strat(x, y, n_classes):
    <source elided>
    for i in range(n_classes):
        s = np.random.choice(idx[y==i], counts[i], replace=True)
        ^

During: resolving callee type: type(CPUDispatcher(<function resample_strat at 0x00000235B2228BF8>))
During: typing of call at C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\trees.py (174)

During: resolving callee type: type(CPUDispatcher(<function resample_strat at 0x00000235B2228BF8>))
During: typing of call at C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\trees.py (174)

During: resolving callee type: type(CPUDispatcher(<function resample_strat at 0x00000235B2228BF8>))
During: typing of call at C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\trees.py (174)

File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\trees.py", line 174:
def build_forest(X, y, n_estimators, bootstrap, ncat, imp_measure,
    <source elided>
        for i in range(start, stop):
            Xtree_, ytree_, _ = resample_strat(X, y, n_classes)

**Comment by AlCorreia** [comment]
Thanks for reporting this. I suspect that your class variable is shaped as a 2D array. Could check if it works if you reshape your class variable to be 1D? For instance, `y = y.reshape(-1)`.

**Comment by N950** [comment]
Thank you for responding,
Yes that fixed the fit(), thanks
