### ISSUE TITLE
model.topc() is throwing an error, if you can help I appreciate it

### ISSUE THREAD

**Issue by N950** [AlCorreia/GeFs#5]
model.topc() is throwing an error, if you can help I appreciate it
tbh I don't understand this traceback, it seems like numba errors are less structured 

Traceback (most recent call last):
  File "model_gefs.py", line 94, in fit
    model.model = model.model.topc()  # Convert to a GeF
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\trees.py", line 522, in topc
    pc.root = SumNode(scope=self.scope, parent=None, n=1)
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\numba\core\dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\numba\core\dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\numba\core\utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x000001D48EBE81D0>.
Failed in nopython mode pipeline (step: nopython mode backend)
Can only insert i64* at [4] in {i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}: got i32*

File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\nodes.py", line 49:
    def __init__(self, parent, scope, type, n):
        <source elided>
        self.sibling = None
        self.scope = scope
        ^

During: lowering "(self).scope = scope" at C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\nodes.py (49)
During: resolving callee type: jitclass.Node#1d48d0204a8<id:int64,parent:OptionalType(DeferredType#2012402805896) i.e. the type 'DeferredType#2012402805896 or None',left_child:OptionalType(DeferredType#2012402805896) i.e. the type 'DeferredType#2012402805896 or None',right_child:OptionalType(DeferredType#2012402805896) i.e. the type 'DeferredType#2012402805896 or None',sibling:OptionalType(DeferredType#2012402805896) i.e. the type 'DeferredType#2012402805896 or None',scope:array(int64, 1d, A),type:unicode_type,n:float64,w:OptionalType(array(float64, 1d, A)) i.e. the type 'array(float64, 1d, A) or None',logw:OptionalType(array(float64, 1d, A)) i.e. the type 'array(float64, 1d, A) or None',comparison:int64,value:array(float64, 1d, A),mean:float64,std:float64,a:float64,b:float64,logcounts:OptionalType(array(float64, 1d, A)) i.e. the type 'array(float64, 1d, A) or None',p:OptionalType(array(float64, 1d, A)) i.e. the type 'array(float64, 1d, A) or None',logp:OptionalType(array(float64, 1d, A)) i.e. the type 'array(float64, 1d, A) or None',upper:array(float64, 1d, A),lower:array(float64, 1d, A)>
During: typing of call at C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\nodes.py (123)

Enable logging at debug level for details.

File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\nodes.py", line 123:
def SumNode(parent, scope, n):
    return Node(parent, scope, 'S', n)
    ^

**Comment by AlCorreia** [comment]
The traceback from numba is not always very informative, unfortunately. It seems that you are passing a scope parameter which has type int32 while it should have been int64.

Though, judging by the traceback you are using a slightly older version of the code. I believe that if you pull the latest version, you will no longer get this error. Alternatively, you can just cast scope to be int64, e.g. `scope = scope.astype(np.int64)`.

**Comment by N950** [comment]
Thank you very much for responding
I switched to the latest version, still getting errors after fit(), I don't understand how the model will train fine but will throw errors at model.topc() 

Am I missing something about input types or something ?

*********** Fit over ***********

  0%|                                                                                                                                                       | 0/100 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "model_gefs.py", line 95, in fit
    model.model = model.model.topc()  # Convert to a GeF
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\trees.py", line 551, in topc
    thr=thr, minstd=minstd, smoothing=smoothing)
  File "C:\Users\asus\anaconda3\envs\dsa2\lib\site-packages\gefs\trees.py", line 351, in tree2pc
    p_left, p_right = add_split(tree_node, pc_node, ncat, smoothing, root)
TypeError: expected instance.jitclass.Split#22dc49d68d0<score:float64,var:int64,threshold:array(float64, 1d, A),surr_var:array(int64, 1d, A),surr_thr:array(float64, 1d, A),surr_go_left:array(bool, 1d, A),surr_blind:bool,left_ids:array(int64, 1d, A),right_ids:array(int64, 1d, A),left_counts:array(int64, 1d, A),right_counts:array(int64, 1d, A),type:unicode_type>, got None

**Comment by AlCorreia** [comment]
Could you maybe share your code? It is hard for me to reproduce your error otherwise.

It seems that your model is not actually training in fact. The error indicates your tree has no splits.

**Comment by N950** [comment]
X, y are random data, y has two classes 0/1


print("\n\ntypes : ")
print("X : ", Xtrain.shape)
print("y : ", ytrain.shape)
print("ncat : ", ncat.shape)
types :
    #  X :  (712, 12)
    #  y :  (712, 1)
    #  ncat :  (1,)
    #  n_estimatiors :  100
model.model = RandomForest(ncat, n_estimators=model.n_estimators)

print("\n\n")

model.model.fit(Xtrain.values, ytrain.values.reshape(-1))

print("\n*********** Fit over ***********\n")

model.model = model.model.topc()  # Convert to a GeF

**Comment by AlCorreia** [comment]
Not sure whether this is the problem, but your `ncat` parameter is not correct. This is supposed to be the number of categories for each variable: if the ith variables is continuous `ncat[i] = 1`, otherwise `ncat[i] = k` where k is the number of categories of the ith variable. That means, in your case, `ncat` should have shape 13 (12 + 1). So it is not just the number of categories of the class variable, but of every variable in your data.

I should actually document this better and add checks for the size of `ncat`. Sorry about that.

**Comment by N950** [comment]
Ok Thank you for responding
Just to make sure, does X have to contain the target column ?? because you said ncat is (12+1) does that mean X has no y column ?

**Comment by AlCorreia** [comment]
No, X still contains only your explanatory variables. The thing is that the model is defined over X and Y, so it needs to know the number of categories of all the variables.

**Comment by N950** [comment]
Thank you very much for your help
Now model.topc() works
